version: 0.0
os: linux
files:
  - source: /
    destnation: /home/ubuntu
    overwrite: yes    
permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
    - location: deploy/scripts/kill_process.sh
      timeout: 100
      runas: ubuntu
  ApplicationStart:
    - location: deploy/scripts/run_process.sh
      timeout: 3600
      runas: ubuntu
